pre_script:
  - source ./hycrypt/.venv/bin/activate

build-job:
  stage: build
  script:
    - python -m build

test-hycrypt:
  stage: test
  script:
    - python ./tests/test_hycrypt.py

test-fycrypt:
  stage: test
  script:
    - python ./tests/test_fycrypt.py

build-docs:
  stage: deploy
  script:
    - make -C docs html

deploy-prod:
  stage: deploy
  script: echo Done
  environment: production