image: python:3.12.4

stages:
  - build
  - test
  - deploy

before_script:
  - python --version
  - pip install virtualenv
  - python -m venv .venv
  - source .venv/bin/activate
  - pip install -r requirements
  - pip install -e .
  - pip show hycrypt

build-job:
  stage: build
  script:
    - python -m build

test-hycrypt:
  stage: test
  script:
    - python tests/test_hycrypt.py

test-fycrypt:
  stage: test
  script:
    - python tests/test_fycrypt.py

build-docs:
  stage: deploy
  script:
    - make -C docs html

deploy-prod:
  stage: deploy
  script: echo Done
  environment: production
